- id: nbformat
  name: nbformat
  description: "Run 'nbformat' on a Jupyter Notebook"
  entry: python -m tensorflow_docs.tools.nbfmt
  language: python
  language_version: python3
  require_serial: true
  types: [jupyter]
  additional_dependencies: []
